server:
  port: 54412

spring:
  application:
    name: auth-service

eureka:
  instance:
    instance-id: auth-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
