server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}

        - id: user-service/admin
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/admin/**
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
            - JwtAuthenticationFilter

jwt:
  secret: jsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkey
  token:
    validity: 3600000