server:
  port: 54412

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://freetier-mysql.cfyxps9nhs1l.ap-northeast-2.rds.amazonaws.com:3306/authsystem
    username: admin
    password: clwmqjrj1028
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: auth-microservice-instance
    hostname: localhost
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

crypto:
  transformation: AES/CBC/PKCS5Padding
  saltlength: 16
  keylength: 256
  iteration: 185000
  key: Dp5BnBuJzdKr3DpEad124BWg3vQ4tbWEtqt4b2b23Egfs1gEgNJ0PIfkKMl322onupt240vH13NY642rg4b7i7m6476r98IebyTWtb4QTb4BTy6wUMimwybzWxe9ww3mdFoem41Dl4G089QgL
  algorithm:
    secretkeyfactory: PBKDF2WithHmacSHA1
    secretkeyspec: AES

jwt:
  secret: jsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkeyjsonsecretkey
  token:
    validity: 3600000